### PR TITLE
test: add test cases from exiftool

### PR DESCRIPTION
**Pull request by Friendseeker**
This PR adds all jpg test cases from https://github.com/exiftool/exiftool

### CODE REVIEW

**Comment by diegomura** [comment]
Needs rebase :)

**Comment by Friendseeker** [comment]
> Needs rebase :)

Shall start rebasing once the tag value PR is merged.

**Comment by diegomura** [comment]
Done!

**Comment by Friendseeker** [comment]
Thanks! Rebased.

**Review by diegomura — APPROVED** [review]
utACK

Thanks!

**Pull request merged**
